// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyCbfPpv6wHJgVa2Re6DSBZu3epXeqXKE',
    appId: '1:101856237640:web:0588a288d417a90f6f207d',
    messagingSenderId: '101856237640',
    projectId: 'socialwebrtc',
    authDomain: 'socialwebrtc.firebaseapp.com',
    storageBucket: 'socialwebrtc.appspot.com',
    measurementId: 'G-XMQXPEVR80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEOJN4JHKPaEjLI2uMhYPjyJIapdauVdA',
    appId: '1:101856237640:android:d20de3bc9e9586756f207d',
    messagingSenderId: '101856237640',
    projectId: 'socialwebrtc',
    storageBucket: 'socialwebrtc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnbBzB78qd09OoQptG58HpfVatOHy1iII',
    appId: '1:101856237640:ios:c032332c34e379416f207d',
    messagingSenderId: '101856237640',
    projectId: 'socialwebrtc',
    storageBucket: 'socialwebrtc.appspot.com',
    iosBundleId: 'com.example.webRtcSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnbBzB78qd09OoQptG58HpfVatOHy1iII',
    appId: '1:101856237640:ios:c032332c34e379416f207d',
    messagingSenderId: '101856237640',
    projectId: 'socialwebrtc',
    storageBucket: 'socialwebrtc.appspot.com',
    iosBundleId: 'com.example.webRtcSocial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyCbfPpv6wHJgVa2Re6DSBZu3epXeqXKE',
    appId: '1:101856237640:web:b4034e5c72d7a14a6f207d',
    messagingSenderId: '101856237640',
    projectId: 'socialwebrtc',
    authDomain: 'socialwebrtc.firebaseapp.com',
    storageBucket: 'socialwebrtc.appspot.com',
    measurementId: 'G-GD9PWJVHQ8',
  );
}
